---
- name: Setup pre-requisite python3 packages
  package:
    name: "{{ lab-manager-injector-yum-dependencies-python3 }}"
    state: present

- name: Setup pre-requisite pip3 packages
  pip:
    name: "{{ lab-manager-injector-pip-dependencies }}"
    state: present
    executable: /usr/bin/pip3

- name: Copy requirements.txt to target for FTL virtualenv
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: "Create virtualenv {{ virtual_env_name }} for Learning Manager"
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: "{{ lab-manager-injector-virtual-env-home }}/{{ lab-manager-injector-virtual-env-name }}"
    virtualenv_site_packages: no
    virtualenv_command: /usr/local/bin/virtualenv

- name: Clone Lab Manager git repo to host
  git:
    repo: "{{ lab-manager-injector-git-repo }}"
    dest: "{{ lab-manager-injector-home }}"
    version: "{{ lab-manager-git-branch | default('main') }}"
    force: yes
  tags:
    - clone

- name: Runs Lab Manager setup playbook
  ignore_errors: yes
  command: ansible-playbook "{{ lab-manager-injector-home}}/{{ lab-manager-injector-setup-file }}"
