---
- name: Setup pre-requisite python3 packages
  package:
    name: "{{ lab_manager_injector_yum_dependencies_python3 }}"
    state: present

- name: Setup pre-requisite pip3 packages
  pip:
    name: "{{ lab_manager_injector_pip_dependencies }}"
    state: present
    executable: /usr/bin/pip3

- name: Copy requirements.txt to target for Lab Manager virtualenv
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: "Create virtualenv {{ virtual_env_name }} for Learning Manager"
  pip:
    requirements: /tmp/requirements.txt
    virtualenv: "{{ lab_manager_injector_virtual_env_home }}/{{ lab_manager_injector_virtual_env_name }}"
    virtualenv_site_packages: no
    virtualenv_command: /usr/local/bin/virtualenv

- name: Clone Lab Manager git repo to host
  git:
    repo: "{{ lab_manager_injector_git_repo }}"
    dest: "{{ lab_manager_injector_home }}"
    version: "{{ lab_manager_git_branch | default('main') }}"
    force: yes
  tags:
    - clone

- name: Runs Lab Manager setup playbook
  ignore_errors: yes
  command: ansible-playbook "{{ lab_manager_injector_home}}/{{ lab_manager_injector_setup_file }}"
